#!/usr/bin/perl
$dir=`pwd`;
chomp $dir;
my $x='';
$x = $dir;
if ($x =~ m!/5.1/!)
{
	$x =~ s!/5.1/!/6.1/!;
}
elsif ($x =~ m!/6.1/!)
{
	$x =~ s!/6.1/!/5.1/!;
}
else 
{
	die "Not in a version'd path";
}

print $x;

