#!/usr/bin/zsh

cd /tmp
rm -rf /tmp/PP1  2>/dev/null
mkdir PP1
cd PP1

scp pp1:~/.cvsrc .
scp pp1:~/.screenrc .
scp pp1:~/.vimrc .
scp pp1:~/.zshrc .
scp -r pp1:~/.vim/plugin .
scp -r pp1:~/bin .

diff -q .cvsrc ~    > difs.txt
diff -q .screenrc ~       >>difs.txt
diff -q .vimrc ~       >>difs.txt
diff -q .zshrc ~       >>difs.txt
diff -q plugin ~/.vim/plugin       >>difs.txt
diff -q bin ~/bin       >>difs.txt
