#!/usr/bin/perl
$dir=`pwd`;
chomp $dir;
my $x='';

$x = 'hpb shared' if ($dir =~ m!/iDirect$!);
$x = 'hpb shared realtime' if ($dir =~ m!/3.1.0.99/.*/iDirect$!);
$x = 'hpb shared embedded' if ($dir =~ m!/7.0-branch/eserver/iDirect$!);
$x = 'hpb shared third_party' if ($dir =~ m!/8.0-branch/.*/iDirect$!);
$x = 'hpb shared third_party' if ($dir =~ m!/vzb/.*/iDirect$!);
$x = 'hpb shared third_party' if ($dir =~ m!/bgp/.*/iDirect$!);
$x = '' if ($dir =~ m!/trunk/eserver/iDirect$!);
$x = "@ARGV" if (scalar @ARGV > 0);


print ("cvs up $x 2>/dev/null\n");
system("cvs up $x 2>/dev/null | grep -v '^\? realtime'");
