#!/usr/bin/perl
$dir=`pwd`;
chomp $dir;
my $x='';
$x = $dir;

my $rev1="eserver" ; my $rev2="phoenix";
#my $rev1="3\.1\.0\.99"; my $rev2="3\.1\.50\.0";

if ($x =~ m!/$rev1/!)
{
	$x =~ s!/$rev1/!/$rev2/!;
}
elsif ($x =~ m!/$rev2/!)
{
	$x =~ s!/$rev2/!/$rev1/!;
}
else 
{
	die "Not in a target'd path";
}


print "cp @ARGV[0] $x/@ARGV[0]\n";
print `cp @ARGV[0] $x/@ARGV[0]`;

