#! /bin/bash


#Link the binaries to my working development directory!




sudo ln -s $h/sarmt/sarmt /usr/sbin/idirect/sarmt
sudo ln -s $h/sada/sada /usr/sbin/idirect/sada
sudo ln -s $h/samnc/samnc /usr/sbin/samnc
sudo ln -s $h/sarouter/sarouter /usr/sbin/idirect/sarouter
sudo ln -s $h/sana/sana /usr/sbin/idirect/sana

