#! /bin/bash

x=/home/bsnyder/work

cd $x
taglist=`find . -name iDirect -type d -maxdepth 3`
for DIR in $taglist
do
	cd $DIR
	rm -rf tags
	/usr/bin/ctags --extra=+fq -R --exclude='shared/tools/*' --exclude='Makefile' --exclude='*/dump_socket/*'  --exclude='*/saa/*' --exclude='hpb/drivers/*' --exclude='*/enc/*' --exclude='*/broadcast*'  --exclude='*/aggronator/*' --exclude='*/remote_handler/*' --exclude='*/ll/*' --exclude='*/network/*' --exclude='*/sar/*' --exclude='hpb/drivers/*' --exclude='hpb/tools/*' --exclude='hpb/test/*' --exclude='hpb/script/*' hpb shared
	cd $x
done
